In [3]:
import pandas as pd
import numpy as np

from sklearn.linear_model import LinearRegression

In [4]:
url = 'https://raw.githubusercontent.com/campusx-official/100-days-of-machine-learning/refs/heads/main/day40-iterative-imputer/50_Startups.csv'
df = np.round(pd.read_csv(url)[['R&D Spend','Administration','Marketing Spend','Profit']]/10000)
np.random.seed(9)
df = df.sample(5)

df

R&D Spend  Administration  Marketing Spend  Profit
21        8.0            15.0             30.0    11.0
37        4.0             5.0             20.0     9.0
2        15.0            10.0             41.0    19.0
14       12.0            16.0             26.0    13.0
44        2.0            15.0              3.0     7.0

In [5]:
df = df.iloc[:,0:-1]
df

R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        4.0             5.0             20.0
2        15.0            10.0             41.0
14       12.0            16.0             26.0
44        2.0            15.0              3.0

In [6]:
df.iloc[1,0] = np.nan
df.iloc[3,1] = np.nan
df.iloc[-1,-1] = np.nan

/var/folders/mp/ktrc96ws30v801fshnxv23mc0000gn/T/ipykernel_1738/766688332.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[1,0] = np.nan
/var/folders/mp/ktrc96ws30v801fshnxv23mc0000gn/T/ipykernel_1738/766688332.py:2: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[3,1] = np.nan
/var/folders/mp/ktrc96ws30v801fshnxv23mc0000gn/T/ipykernel_1738/766688332.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.iloc[-1,-1] = 

In [7]:
df.head()

R&D Spend  Administration  Marketing Spend
21        8.0            15.0             30.0
37        NaN             5.0             20.0
2        15.0            10.0             41.0
14       12.0             NaN             26.0
44        2.0            15.0              NaN

In [8]:
# Step 1 - Impute all missing values with mean of respective col

df0 = pd.DataFrame()
df0['R&D Spend'] = df['R&D Spend'].fillna(df['R&D Spend'].mean())
df0['Administration'] = df['Administration'].fillna(df['Administration'].mean())
df0['Marketing Spend'] = df['Marketing Spend'].fillna(df['Marketing Spend'].mean())

In [9]:
# 0th iteration
df0

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37       9.25            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [10]:
#remove the coll imputed value
df1 = df0.copy()

df1.iloc[1,0] = np.nan

df1

R&D Spend  Administration  Marketing Spend
21        8.0           15.00            30.00
37        NaN            5.00            20.00
2        15.0           10.00            41.00
14       12.0           11.25            26.00
44        2.0           15.00            29.25

In [11]:
# use first 3 rows to build a model and use the last for prediction

x = df1.iloc[[0,2,3,4],1:3]
x

Administration  Marketing Spend
21           15.00            30.00
2            10.00            41.00
14           11.25            26.00
44           15.00            29.25

In [12]:
y = df1.iloc[[0,2,3,4],0]
y

21     8.0
2     15.0
14    12.0
44     2.0
Name: R&D Spend, dtype: float64

In [13]:
df1.iloc[1,1:].values.reshape(1,2)

array([[ 5., 20.]])

In [14]:
lr = LinearRegression()
lr.fit(x,y)
lr.predict(df1.iloc[1,1:].values.reshape(1,2))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.14158651])

In [15]:
df1.iloc[1,0] = 23.14

In [16]:
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.25            26.00
44       2.00           15.00            29.25

In [17]:
df1.iloc[3,1] = np.nan

df1

R&D Spend  Administration  Marketing Spend
21       8.00            15.0            30.00
37      23.14             5.0            20.00
2       15.00            10.0            41.00
14      12.00             NaN            26.00
44       2.00            15.0            29.25

In [18]:
x = df1.iloc[[0,1,2,4],[0,2]]
x

R&D Spend  Marketing Spend
21       8.00            30.00
37      23.14            20.00
2       15.00            41.00
44       2.00            29.25

In [19]:
y = df1.iloc[[0,1,2,4],1]
y

21    15.0
37     5.0
2     10.0
44    15.0
Name: Administration, dtype: float64

In [20]:
lr = LinearRegression()
lr.fit(x,y)
lr.predict(df1.iloc[3,[0,2]].values.reshape(1,2))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([11.06331285])

In [21]:
df1.iloc[3,1] = 11.06

In [22]:
df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00            30.00
37      23.14            5.00            20.00
2       15.00           10.00            41.00
14      12.00           11.06            26.00
44       2.00           15.00            29.25

In [23]:
#remove the col3 imputed value
df1.iloc[4, -1] = np.nan

df1

R&D Spend  Administration  Marketing Spend
21       8.00           15.00             30.0
37      23.14            5.00             20.0
2       15.00           10.00             41.0
14      12.00           11.06             26.0
44       2.00           15.00              NaN

In [24]:
x = df1.iloc[0:4, 0:2]
x

R&D Spend  Administration
21       8.00           15.00
37      23.14            5.00
2       15.00           10.00
14      12.00           11.06

In [25]:
y = df1.iloc[0:4, -1]
y

21    30.0
37    20.0
2     41.0
14    26.0
Name: Marketing Spend, dtype: float64

In [26]:
lr = LinearRegression()
lr.fit(x,y)
m = lr.predict(df1.iloc[4,0:2].values.reshape(1,-1))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


In [27]:
df1.iloc[4,-1] = m

In [28]:
m

array([31.56351448])

In [29]:
# subtraction 0th iteration from 1st iteration

df1 - df0

R&D Spend  Administration  Marketing Spend
21       0.00            0.00         0.000000
37      13.89            0.00         0.000000
2        0.00            0.00         0.000000
14       0.00           -0.19         0.000000
44       0.00            0.00         2.313514

In [30]:
df2 = df1.copy()
df2.iloc[1,0] = np.nan

df2

R&D Spend  Administration  Marketing Spend
21        8.0           15.00        30.000000
37        NaN            5.00        20.000000
2        15.0           10.00        41.000000
14       12.0           11.06        26.000000
44        2.0           15.00        31.563514

In [29]:
x = df2.iloc[[0,2,3,4],1:3]
y = df2.iloc[[0,2,3,4],0]

lr = LinearRegression()
lr.fit(x,y)
lr.predict(df2.iloc[1,1:].values.reshape(1,2))

/opt/anaconda3/lib/python3.13/site-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([23.7883775])

In [30]:
df2.iloc[1,0] = 23.78

In [31]:
df2

R&D Spend  Administration  Marketing Spend
21       8.00           15.00        30.000000
37      23.78            5.00        20.000000
2       15.00           10.00        41.000000
14      12.00           11.06        26.000000
44       2.00           15.00        31.563514

In [34]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]
lr = LinearRegression()
lr.fit(X,y)
m = lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))
df2.iloc[3,1] = m
df3 = df2.copy()
    
df3.iloc[1,0] = np.nan
X = df3.iloc[[0,2,3,4],1:3]
y = df3.iloc[[0,2,3,4],0]
lr = LinearRegression()
lr.fit(X,y)
m = lr.predict(df3.iloc[1,1:].values.reshape(1,2)
df3.iloc[1,0] = m
    
df3.iloc[3,1] = np.nan
X = df3.iloc[[0,1,2,4],[0,2]]
y = df3.iloc[[0,1,2,4],1]
lr = LinearRegression()
lr.fit(X,y)
m = lr.predict(df3.iloc[3,[0,2]].values.reshape(1,2))
df3.iloc[3,1] = m

df3.iloc[4,-1] = np.nan
X = df3.iloc[0:4,0:2]
y = df3.iloc[0:4,-1]
lr = LinearRegression()
lr.fit(X,y)
m = lr.predict(df3.iloc[4,0:2].values.reshape(1,2))
df3.iloc[4,-1] = m

_IncompleteInputError: incomplete input (3482609035.py, line 1)

In [ ]:
df2.iloc[3,1] = np.nan
X = df2.iloc[[0,1,2,4],[0,2]]
y = df2.iloc[[0,1,2,4],1]
lr = LinearRegression()
lr.fit(X,y)
m = lr.predict(df2.iloc[3,[0,2]].values.reshape(1,2))
df2.iloc[3,1] = m